language: python
python:
    - 2.7
    - 3.6
    - 3.7
    - 3.8
    - 3.9-dev
install:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
script:
    - nose2 --with-coverage
after_success:
    - coveralls
